#!/bin/bash
set -euxo pipefail

sudo apt-get update && sudo apt-get install -y --no-install-recommends \
make qtscript5-dev qttools5-dev-tools qtmultimedia5-dev "$TRIK_PYTHON_VERSION"-dev qtbase5-private-dev bear

